### ISSUE TITLE
[FEATURE] 친구 뷰 제작

### ISSUE THREAD

**Issue by HwangHyeryeong** [sobeeLOG/front-end#10]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 친구 목록을 조회하는 뷰 만들기
- 친구 요청 목록을 조회하는 뷰 만들기
- 친구 검색 뷰 만들기

## TODO

- [x] 친구 관련 컴포넌트 만들기
