### ISSUE TITLE
[FEATURE] 소비내역 작성 api 연동

### ISSUE THREAD

**Issue by choiyoorim** [sobeeLOG/front-end#12]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 소비내역 작성 api 연동하기 

## TODO

- [ ] 소비내역 작성 post api에 데이터 한번에 전달 -> onChange 및 setState 활용해야할듯
- [ ] 버튼 onClick에 post api 연결
