### ISSUE TITLE
[FEATURE] 친구 신청 답신 API 연결

### ISSUE THREAD

**Issue by HwangHyeryeong** [sobeeLOG/front-end#18]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 친구 신청에 대한 답신 API 연결(수락 or 거절)

## TODO

- [ ] 수락/거절 버튼 눌렀을 때 API 호출하도록
