### ISSUE TITLE
[FEATURE] 소비내역 상세창 뷰 제작

### ISSUE THREAD

**Issue by choiyoorim** [sobeeLOG/front-end#23]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 소비내역 상세창 뷰 
- 댓글 및 답댓글 뷰
- 피드나 캘린더에서 onClick시 실행될 수 있도록 하기 

## TODO

- [ ] 댓글 및 답댓글 분리
- [ ] 피드나 캘린더 onClick 함수 설정
