### ISSUE TITLE
[FEATURE] 소비내역 피드 뷰 제작

### ISSUE THREAD

**Issue by choiyoorim** [sobeeLOG/front-end#3]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 캘린더 창에서 만든 소비내역 component 재활용해서 피드 만들기

## TODO

- [ ] 기존 컴포넌트랑 다른점 파악하기 -> 없게끔 피그마 수정하기
- [ ] 컴포넌트로 연결해서 리스트 map하기
- [ ] 라우팅 해놓기
