### ISSUE TITLE
[FEATURE] Emoticon POST api 연결

### ISSUE THREAD

**Issue by choiyoorim** [sobeeLOG/front-end#30]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- emoticon post api 연결
- api 작동부터 테스트

## TODO

- [x] count 작동 확인
- [ ] 작동 테스트 
- [ ] api 연결
- [ ] onClick 후 svg 색상 바꾸는 로직 추가
