### ISSUE TITLE
[FEATURE] 회원가입, 로그인 api 연결 및 로그인 유지

### ISSUE THREAD

**Issue by choiyoorim** [sobeeLOG/front-end#35]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 이런 걸 할거야

## TODO

- [ ] 회원가입 api 연결
- [ ] 로그인 api 연결
- [ ] 세션에 로그인 정보 저장 후 페이지마다 유저 정보로 변환
