### ISSUE TITLE
[FEATURE] 친구 검색 API 연결

### ISSUE THREAD

**Issue by HwangHyeryeong** [sobeeLOG/front-end#37]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 친구 검색하는 API 연결

## TODO

- [ ] 친구 검색하는 API 연결
