### ISSUE TITLE
[BUG] 사용자 검색 API 조건 변경에 따른 수정

### ISSUE THREAD

**Issue by HwangHyeryeong** [sobeeLOG/front-end#42]
## ✅ Bug Report check list

- [x] 이슈 제목: [BUG] '버그 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## BUG 개요

- 사용자 검색 API 조건 변경에 따른 요청값 변경

## TODO

- [ ] 사용자 검색 요청 변경
