### ISSUE TITLE
[FEATURE] 소비내역 작성 뷰 제작

### ISSUE THREAD

**Issue by choiyoorim** [sobeeLOG/front-end#5]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 소비내역 작성 창 만들기
- 외부 클릭시 창 닫히는 기능 추가하기
- post 할 때 한번에 데이터를 보낼 수 있도록 setState로 상태 관리하기

## TODO

- [ ] 소비내역 작성 클릭 버튼 추가
- [ ] 버튼 클릭시 작성창 뜨게 하는 onClick 함수 추가
- [ ] 소비내역 작성창 뷰 만들기
- [ ] post 바로 직전 데이터 값 만들어두기
