### ISSUE TITLE
[FEATURE] 서버 axios 연결 추가 

### ISSUE THREAD

**Issue by choiyoorim** [sobeeLOG/front-end#7]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 서버 api 연결을 위한 axios 작업할 예정

## TODO

- [ ] 서버 git pull을 통해서 지금까지의 서버 작업을 돌려야함
- [ ] axios 설정(ip를 통해)
