### ISSUE TITLE
[FEATURE] 소비내역 api 연결 

### ISSUE THREAD

**Issue by choiyoorim** [sobeeLOG/front-end#9]
## ✅ Feature Request check list

- [x] 이슈 제목: [FEATURE] '기능 내용 상세'
- [x] Assignees, Label을 붙여주세요.

## 추가할 기능 개요

- 소비내역을 가져오는 api들을 연결합니다. 

## TODO

- [ ] 피드 부분 소비내역 조회 api 연결
- [ ] 일별 소비내역 조회 api 연결
